### ISSUE TITLE
Determine how to integrate GunJS.

### ISSUE THREAD

**Issue by andres-holguin** [gsewsankar/fwee-dev#2]

**Comment by andres-holguin** [comment]
GunJS is a distributed database API. It is designed to work as a Firebase alternative, exposing a public interface that is similar to that of a document-based database. The underlying tech of GunJS uses the same conflict-resolution and encryption algorithms, among others, that would be used in a blockchain protocol.

GunJS can be implemented in this project by replacing its dependency on Firebase Cloudstore Database solutions.

**Comment by andres-holguin** [comment]
In Order to close this Issue, please check off your approval, or comment with questions for further discussion.

- [x] @andres-holguin 
- [ ] @gsewsankar 
- [ ] @skbt27i 
- [ ] @robertcasanova99

**Comment by gsewsankar** [comment]
We'll look at GunJS and discuss it in the meeting on Tuesday. To me, it seems like the best option.
